"""Shadow package for mlx_lm.models.gemma4. FROZEN.

This is the only wiring point. When the harness does
`import mlx_models.gemma4`, this __init__ runs and:

  1. Imports the upstream `mlx_lm.models.gemma4` and its text
     submodule.
  2. Loads the 4 modifiable files (model.py, linear.py, weights.py,
     experts.py). Each one installs its override on the appropriate
     module — global `nn.Linear`, the switch_layers module, or the
     gemma4_text module's `Model` class.
  3. Re-exports the (now-patched) `mlx_lm.models.gemma4` under our
     name. From the harness's perspective, `mlx_models.gemma4` IS
     `mlx_lm.models.gemma4`, with our overrides applied.

Participants do NOT edit this file. Edit the 4 modifiable files only.

Order of operations matters:
  - `linear` and `experts` are installed before `model` because the
    model class construction (via __init__ of its submodules) calls
    nn.Linear and SwitchGLU; those must already point at our classes
    when construction happens.
  - The process is dedicated to running one model, so the global
    `nn.Linear` patch is safe — no other code in the process needs
    the original mlx.nn.Linear.
"""
from __future__ import annotations

# We need to import mlx_lm.models.gemma4 first to make sure its
# submodules (gemma4_text, switch_layers) are loaded into sys.modules.
# This way, when model.py and experts.py do `import
# mlx_lm.models.gemma4_text`, they get the same module objects the
# harness will use.
import mlx_lm.models.gemma4 as _upstream_gemma4  # noqa: F401
import mlx_lm.models.gemma4_text as _upstream_text  # noqa: F401
import mlx_lm.models.switch_layers as _upstream_switch  # noqa: F401
import mlx.nn as _nn  # noqa: F401

# Install the modifiable overrides. Order: primitives first, then the
# model class that uses them.
from . import linear as _linear_module
from . import experts as _experts_module
from . import model as _model_module
from . import weights as _weights_module

# Apply primitive-level patches (process-wide; safe because the
# process is dedicated to this model).
_linear_module.install()         # mlx.nn.Linear -> our Linear
_experts_module.install()        # mlx_lm.models.switch_layers.* -> ours

# The Model class patch is a no-op for the baseline (it just re-binds
# to the same upstream class), but it gives the participant a hook
# point: if they redefine Model in model.py, the upstream module
# picks up their version the next time anyone imports
# `mlx_lm.models.gemma4_text.Model`.
_upstream_text.Model = _model_module.Model

# Public surface of the shadow package. The harness imports
# `mlx_models.gemma4` and uses these names.
__all__ = [
    "Model",
    "ModelArgs",
    "Linear",
    "SwitchGLU",
    "SwitchLinear",
    "QuantizedSwitchLinear",
    "load_weights",
    "load_config",
    "sanitize",
]

# Resolve the public names to point at our (now-installed) classes.
Model = _model_module.Model
ModelArgs = _model_module.ModelArgs
Linear = _linear_module.Linear
SwitchGLU = _experts_module.SwitchGLU
SwitchLinear = _experts_module.SwitchLinear
QuantizedSwitchLinear = _experts_module.QuantizedSwitchLinear
load_weights = _weights_module.load_weights
load_config = _weights_module.load_config
sanitize = _model_module.sanitize

# Make `import mlx_models.gemma4 as X; X.Model` resolve to the same
# object the harness would get from `from mlx_lm.models.gemma4 import
# Model` AFTER our patches. We achieve this by aliasing the upstream
# module's public attributes at this point.
_upstream_gemma4.Model = _model_module.Model
_upstream_gemma4.ModelArgs = _model_module.ModelArgs
_upstream_gemma4.sanitize = _model_module.sanitize
_upstream_gemma4.load_weights = _weights_module.load_weights
